# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsDoctor < Formula
  desc "Powerful open-source CLI to audit security, costs, and best practices in AWS. 🩺 ☁️"
  homepage "https://github.com/elC0mpa/aws-doctor"
  version "2.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elC0mpa/aws-doctor/releases/download/v2.5.0/aws-doctor_2.5.0_darwin_amd64.tar.gz"
      sha256 "db6bed35a78d48b56db66085d5f118e82fa125350767bc7563c865bd556a9236"

      define_method(:install) do
        bin.install "aws-doctor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elC0mpa/aws-doctor/releases/download/v2.5.0/aws-doctor_2.5.0_darwin_arm64.tar.gz"
      sha256 "87d81412d749761ab7a7bc369b5ba2bf42c1beb879660c578b6223285e98319f"

      define_method(:install) do
        bin.install "aws-doctor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elC0mpa/aws-doctor/releases/download/v2.5.0/aws-doctor_2.5.0_linux_amd64.tar.gz"
      sha256 "c916f964a9f9270ce659719214df10eef728651662305d8421646ab0e3b38839"
      define_method(:install) do
        bin.install "aws-doctor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elC0mpa/aws-doctor/releases/download/v2.5.0/aws-doctor_2.5.0_linux_arm64.tar.gz"
      sha256 "927b89cac616659a36df855436a5ba4df88a69b27e7623d6e957b6fbf073e6fc"
      define_method(:install) do
        bin.install "aws-doctor"
      end
    end
  end

  test do
    system "#{bin}/aws-doctor --version"
  end
end
