# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsDoctor < Formula
  desc "Powerful open-source CLI to audit security, costs, and best practices in AWS. 🩺 ☁️"
  homepage "https://github.com/elC0mpa/aws-doctor"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elC0mpa/aws-doctor/releases/download/v1.8.0/aws-doctor_1.8.0_darwin_amd64.tar.gz"
      sha256 "2080ba29cf21c5fb2b5b67c803c25d88c37cf01e03da3e9b1ad576fa016cc186"

      def install
        bin.install "aws-doctor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elC0mpa/aws-doctor/releases/download/v1.8.0/aws-doctor_1.8.0_darwin_arm64.tar.gz"
      sha256 "c394bd575f5546e26e8627fe9e09bc4b948ae616d53bc0efb3e61d2f7c0cc83e"

      def install
        bin.install "aws-doctor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elC0mpa/aws-doctor/releases/download/v1.8.0/aws-doctor_1.8.0_linux_amd64.tar.gz"
      sha256 "44d3bbfdb788a3b071ff8c61e3cebbebeae7bf38537931a6aa7d7c3df7234b26"
      def install
        bin.install "aws-doctor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elC0mpa/aws-doctor/releases/download/v1.8.0/aws-doctor_1.8.0_linux_arm64.tar.gz"
      sha256 "f44bba0fc7d599645730ff25f6ba6c5c1f2f8c6a8cb065ece1b100ab99c0e522"
      def install
        bin.install "aws-doctor"
      end
    end
  end

  test do
    system "#{bin}/aws-doctor --version"
  end
end
